// Generated by gencpp from file open_base/KinematicsForwardRequest.msg
// DO NOT EDIT!


#ifndef OPEN_BASE_MESSAGE_KINEMATICSFORWARDREQUEST_H
#define OPEN_BASE_MESSAGE_KINEMATICSFORWARDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <open_base/Velocity.h>

namespace open_base
{
template <class ContainerAllocator>
struct KinematicsForwardRequest_
{
  typedef KinematicsForwardRequest_<ContainerAllocator> Type;

  KinematicsForwardRequest_()
    : input()  {
    }
  KinematicsForwardRequest_(const ContainerAllocator& _alloc)
    : input(_alloc)  {
  (void)_alloc;
    }



   typedef  ::open_base::Velocity_<ContainerAllocator>  _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::open_base::KinematicsForwardRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::open_base::KinematicsForwardRequest_<ContainerAllocator> const> ConstPtr;

}; // struct KinematicsForwardRequest_

typedef ::open_base::KinematicsForwardRequest_<std::allocator<void> > KinematicsForwardRequest;

typedef boost::shared_ptr< ::open_base::KinematicsForwardRequest > KinematicsForwardRequestPtr;
typedef boost::shared_ptr< ::open_base::KinematicsForwardRequest const> KinematicsForwardRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::open_base::KinematicsForwardRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::open_base::KinematicsForwardRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::open_base::KinematicsForwardRequest_<ContainerAllocator1> & lhs, const ::open_base::KinematicsForwardRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input == rhs.input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::open_base::KinematicsForwardRequest_<ContainerAllocator1> & lhs, const ::open_base::KinematicsForwardRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace open_base

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::open_base::KinematicsForwardRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::open_base::KinematicsForwardRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::open_base::KinematicsForwardRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::open_base::KinematicsForwardRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::open_base::KinematicsForwardRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::open_base::KinematicsForwardRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::open_base::KinematicsForwardRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29bd53674d0c2a2c975ed4e5dc6ba2a3";
  }

  static const char* value(const ::open_base::KinematicsForwardRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29bd53674d0c2a2cULL;
  static const uint64_t static_value2 = 0x975ed4e5dc6ba2a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::open_base::KinematicsForwardRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "open_base/KinematicsForwardRequest";
  }

  static const char* value(const ::open_base::KinematicsForwardRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::open_base::KinematicsForwardRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "open_base/Velocity input\n"
"\n"
"================================================================================\n"
"MSG: open_base/Velocity\n"
"float64 v_left\n"
"float64 v_back\n"
"float64 v_right\n"
;
  }

  static const char* value(const ::open_base::KinematicsForwardRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::open_base::KinematicsForwardRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KinematicsForwardRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::open_base::KinematicsForwardRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::open_base::KinematicsForwardRequest_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    s << std::endl;
    Printer< ::open_base::Velocity_<ContainerAllocator> >::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPEN_BASE_MESSAGE_KINEMATICSFORWARDREQUEST_H
